export const INTERESTS = {
  1: 'communities',
  2: 'development',
  3: 'dsa/cp',
  4: 'web',
  5: 'mobile',
  6: 'web3',
  7: 'AI/ML/DS',
  8: 'devops',
  9: 'cloud',
  10: 'startups',
  11: 'entrepreneurship',
  12: 'content-creation',
  13: 'finance',
  14: 'crypto',
  15: 'iot',
  16: 'cybersecurity',
  17: 'game-dev',
  18: 'design',
  19: 'open-source',
}
